version: '3'
services:
  deepstream:
    # v4.0.0-rc.2-alpine, 3.1.0 = latest
    image: deepstreamio/deepstream.io:v4.0.0-rc.2-alpine
    ports:
      - "6020:6020"
      - "8080:8080"
    volumes:
      - ./deepstream/conf:/opt/deepstream/conf
    #command: ./deepstream start --disable-auth --disable-permissions

  .deepstream-client: &deepstream-client  
    image: foo
    environment:
      DEEPSTREAM_URL: deepstream:6020
      DEEPSTREAM_USER: userA
      DEEPSTREAM_PWD: ${DEEPSTREAM_PWD}
      DEEPSTREAM_EVENT: test
    depends_on:
      - deepstream

  dotnet:
    build:
      context: ./dotnet
    <<: *deepstream-client   

  java:
    build:
      context: ./java
    <<: *deepstream-client   
