version: '3'
services:
  deepstream:
    # v4.0.0-rc.2-alpine, 3.1.0 = latest
    image: deepstreamio/deepstream.io:v4.0.0-rc.2-alpine
    ports:
      - "6020:6020"
      - "8080:8080"
    command: ./deepstream start --disable-auth --disable-permissions
  
  dotnet:
    build:
      context: ./dotnet
    environment:
      DEEPSTREAM_URL: deepstream:6020
    depends_on:
      - deepstream
  
  java:
    build:
      context: ./java
    environment:
      DEEPSTREAM_URL: deepstream:6020
    depends_on:
      - deepstream
